# Template for Ansible Vault secrets file
# Encrypt this file using: ansible-vault encrypt secrets.yml
# DO NOT COMMIT THIS FILE TO VERSION CONTROL

# MongoDB secrets
vault_mongodb_root_username: "root"
vault_mongodb_root_password: "your_mongodb_root_password_here"

# PostgreSQL secrets
vault_postgres_root_username: "postgres"
vault_postgres_root_password: "your_postgres_root_password_here"

# Redis-Stack secrets
vault_redis_default_username: "default"
vault_redis_default_password: "your_redis_default_password_here"

# Kafka secrets
vault_kafka_sasl_username: "root"
vault_kafka_sasl_password: "your_kafka_sasl_password_here"