# Kubernetes secrets for Derkino infrastructure
# This file should be encrypted with ansible-vault

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: infrastructure
type: Opaque
data:
  username: YWRtaW4=  # admin
  password: cGFzc3dvcmQ=  # password

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: infrastructure
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=  # password

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: infrastructure
type: Opaque
data:
  redis-password: cGFzc3dvcmQ=  # password