apiVersion: v1
kind: Service
metadata:
  name: generative-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8083
      targetPort: 8000
      protocol: TCP
  selector:
    app: generative-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generative-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generative-service
  template:
    metadata:
      labels:
        app: generative-service
    spec:
      containers:
      - name: generative-service
        image: gryphon2411/derkino-generative_service:latest
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: HUGGINGFACE_HUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface-hub-access-token
              key: token
        - name: GENERATIVE_MODEL_NAME
          # Possible values: gemma, phi3, mixtral8x7b
          value: mixtral8x7b
        - name: DATA_SERVICE_URL
          value: http://data-service:8082/api/v1/data

        - name: RABBITMQ_HOST_ADDRESS
          value: rabbitmq.rabbitmq-system
        - name: RABBITMQ_HOST_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: derkino-services
        - name: RABBITMQ_PASSWORD
          value: 2gGCIz8qgvuUzQfW
        - name: RABBITMQ_VHOST
          value: "/"