# Kafka secrets management

- name: Create Kafka Kubernetes Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: kafka-sasl-credentials
        namespace: kafka-system
      type: Opaque
      data:
        username: "{{ vault_kafka_sasl_username | b64encode | default('root' | b64encode) }}"
        password: "{{ vault_kafka_sasl_password | b64encode }}"
