# Secrets management tasks with Ansible Vault support

- name: Include MongoDB secrets
  ansible.builtin.include_tasks: mongodb.yml

- name: Include PostgreSQL secrets
  ansible.builtin.include_tasks: postgresql.yml

- name: Include Redis-Stack secrets
  ansible.builtin.include_tasks: redis-stack.yml

- name: Include Kafka secrets
  ansible.builtin.include_tasks: kafka.yml
