# Secrets management tasks with Ansible Vault support

- name: Ensure vault password file exists
  stat:
    path: "{{ vault_password_file }}"
  register: vault_password_stat

- name: Create vault password file if missing
  copy:
    content: "{{ vault_password }}"
    dest: "{{ vault_password_file }}"
    mode: 0600
  when: not vault_password_stat.stat.exists

- name: Decrypt secrets file
  command: ansible-vault decrypt "{{ secrets_file }}" --vault-password-file "{{ vault_password_file }}"
  when: secrets_file_encrypted | default(true)

- name: Create Kubernetes secrets from vault
  command: kubectl apply -f "{{ secrets_file }}" -n {{ secrets_namespace }}

- name: Re-encrypt secrets file
  command: ansible-vault encrypt "{{ secrets_file }}" --vault-password-file "{{ vault_password_file }}"
  when: secrets_file_encrypted | default(true)