# Secrets management tasks with Ansible Vault support

- name: Ensure vault password file exists
  ansible.builtin.stat:
    path: "{{ secrets_vault_password_file }}"
  register: secrets_vault_password_stat

- name: Create vault password file if missing
  ansible.builtin.copy:
    content: "{{ secrets_vault_password }}"
    dest: "{{ secrets_vault_password_file }}"
    mode: "0600"
  when: not secrets_vault_password_stat.stat.exists

- name: Decrypt secrets file
  ansible.builtin.command: ansible-vault decrypt "{{ secrets_file }}" --vault-password-file "{{ secrets_vault_password_file }}"
  when: secrets_file_encrypted | default(true)
  changed_when: false

- name: Create Kubernetes secrets from vault
  ansible.builtin.command: kubectl apply -f "{{ secrets_file }}" -n {{ secrets_namespace }}
  changed_when: false

- name: Re-encrypt secrets file
  ansible.builtin.command: ansible-vault encrypt "{{ secrets_file }}" --vault-password-file "{{ secrets_vault_password_file }}"
  when: secrets_file_encrypted | default(true)
  changed_when: false
