# Secrets management tasks with Ansible Vault support

- name: Load secrets variables (with vault support)
  ansible.builtin.include_vars:
    file: "{{ secrets_file }}"
  when: secrets_file_encrypted | default(false) and secrets_file_exists | default(false)
  changed_when: false

- name: Include MongoDB secrets
  ansible.builtin.include_tasks: mongodb.yml

- name: Include PostgreSQL secrets
  ansible.builtin.include_tasks: postgresql.yml

- name: Include Redis-Stack secrets
  ansible.builtin.include_tasks: redis-stack.yml

- name: Include Kafka secrets
  ansible.builtin.include_tasks: kafka.yml
