# MongoDB secrets management

- name: Create MongoDB Kubernetes Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: mongodb-root-user-credentials
        namespace: mongodb-system
      type: Opaque
      data:
        username: "{{ vault_mongodb_root_username | b64encode | default('root' | b64encode) }}"
        password: "{{ vault_mongodb_root_password | b64encode }}"