# PostgreSQL secrets management

- name: Create PostgreSQL Kubernetes Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-root-user-credentials
        namespace: postgres-system
      type: Opaque
      data:
        username: "{{ vault_postgres_root_username | b64encode | default('postgres' | b64encode) }}"
        password: "{{ vault_postgres_root_password | b64encode }}"
