# Redis-Stack secrets management

- name: Create Redis-Stack Kubernetes Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: redis-stack-default-user-credentials
        namespace: redis-stack-system
      type: Opaque
      data:
        username: "{{ vault_redis_default_username | b64encode | default('default' | b64encode) }}"
        password: "{{ vault_redis_default_password | b64encode }}"