# Main deployment playbook for Derkino

---
- name: Deploy Derkino Application
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/all/vars.yml
    - environments/{{ environment }}.yml

  roles:
    - common
    - kubernetes
    - { role: helm, when: "migration_enabled is not defined or migration_enabled == false" }
    - { role: migration, when: "migration_enabled is defined and migration_enabled == true" }
    - secrets
    - ingress