---
name: Derkino Infrastructure Validation

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'infrastructure/**'
      - '.github/workflows/derkino-infrastructure.yaml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'infrastructure/**'
      - '.github/workflows/derkino-infrastructure.yaml'

jobs:
  validate-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'         

      - name: Scan for Secrets with TruffleHog
        uses: trufflesecurity/trufflehog@v3.90.11
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --only-verified

      - name: Lint YAML Files
        run: |
          pip install yamllint
          yamllint infrastructure/ -c infrastructure/ansible/.yamllint

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Set up Helm Repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build infrastructure/helm-charts/derkino-infrastructure/

      - name: Verify Chart.lock is Current
        run: |
          # Fail if Chart.lock was modified by dependency build
          git diff --exit-code infrastructure/helm-charts/derkino-infrastructure/Chart.lock

      - name: Lint Helm Charts
        run: |
          helm lint --with-subcharts infrastructure/helm-charts/derkino-infrastructure/
          helm lint infrastructure/helm-charts/derkino-services/
          helm lint infrastructure/helm-charts/derkino-ui/

      - name: Validate Helm Templates
        run: |
          # The "helm template" command is a great smoke test for chart syntax
          helm template test-infra infrastructure/helm-charts/derkino-infrastructure/ > /dev/null
          helm template test-services infrastructure/helm-charts/derkino-services/ > /dev/null
          helm template test-ui infrastructure/helm-charts/derkino-ui/ > /dev/null

      - name: Validate Ansible Playbooks
        uses: ansible/ansible-lint@v25.9.2
        with:
          working_directory: "infrastructure/ansible"

      - name: Ansible Playbook Syntax Check
        run: |
          pip install ansible
          ansible-galaxy collection install -r infrastructure/ansible/collections/requirements.yml
          cd infrastructure/ansible
          ansible-playbook --syntax-check deploy.yml -e "deployment_environment=local"
