# The name of this workflow.
name: derkino data service ci

on:
  # Specifies that this workflow should run on every push event for the branches in the list.
  push:
    branches:
      - master
    paths:
      - services/spring-boot/data_service/**
  # Specifies that this workflow should run on every pull request event targeting the branches in the list.
  pull_request:
    branches:
      - master
    paths:
      - services/spring-boot/data_service/**


# Creates a job ID (build) and declares the type of machine that the job should run on.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository on the build machine.
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      # Signs in to Docker Hub, using the "Docker Login" action and your Docker Hub credentials.
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Creates a BuildKit builder instance using the "Docker Setup Buildx" action.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Builds the container image and pushes it to the Docker Hub repository, using "Build and push Docker images".
      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          # The build context (https://docs.docker.com/build/building/context/), default is "."
          context: services/spring-boot/
          # Filepath to the Dockerfile, default is "./Dockerfile"
          file: services/spring-boot/data_service/Dockerfile
          # Tells the action to upload the image to a registry after building it.
          push: true
          # Tags that specify where to push the image.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/derkino-data_service:latest