---
name: Derkino Infrastructure Validation

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'deployment/**'
      - '.github/workflows/derkino-infrastructure.yaml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'deployment/**'
      - '.github/workflows/derkino-infrastructure.yaml'

jobs:
  validate-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Using a more current Python version

      - name: Install Python Dependencies
        run: pip install yamllint

      - name: Lint YAML Files
        run: yamllint .

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Set up Helm Repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build deployment/helm-charts/derkino-infrastructure/

      - name: Lint Helm Charts
        run: |
          helm lint --with-subcharts deployment/helm-charts/derkino-infrastructure/
          helm lint deployment/helm-charts/derkino-services/
          helm lint deployment/helm-charts/derkino-ui/

      - name: Validate Ansible Playbooks
        uses: ansible/ansible-lint@v25.9.2
        env:
          ANSIBLE_ROLES_PATH: "deployment/ansible/roles"

      - name: Validate Helm Templates
        run: |
          # The "helm template" command is a great smoke test for chart syntax
          helm template test-infra deployment/helm-charts/derkino-infrastructure/ > /dev/null
          helm template test-services deployment/helm-charts/derkino-services/ > /dev/null
          helm template test-ui deployment/helm-charts/derkino-ui/ > /dev/null
