---
name: Derkino Infrastructure Validation

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'deployment/**'
      - '.github/workflows/derkino-infrastructure.yaml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'deployment/**'
      - '.github/workflows/derkino-infrastructure.yaml'

jobs:
  validate-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Using a more current Python version

      - name: Install Python Dependencies
        run: pip install yamllint

      - name: Scan for Secrets with TruffleHog
        uses: trufflesecurity/trufflehog@v3.90.11
        with:
          # Scan the entire repository filesystem git history.
          path: ./

          # Scans only the changes pull requests changes.
          # These inputs are ignored on 'push' events, so it's safe to include.
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          
          # Pass extra CLI arguments. This is the most important part.
          # --only-verified: Reduces false positives by checking if secrets are active.
          extra_args: --only-verified

      - name: Lint YAML Files
        run: yamllint deployment/ -c deployment/ansible/.yamllint

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.0'

      - name: Set up Helm Repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency build deployment/helm-charts/derkino-infrastructure/

      - name: Verify Chart.lock is Current
        run: |
          # Fail if Chart.lock was modified by dependency build
          git diff --exit-code deployment/helm-charts/derkino-infrastructure/Chart.lock

      - name: Lint Helm Charts
        run: |
          helm lint --with-subcharts deployment/helm-charts/derkino-infrastructure/
          helm lint deployment/helm-charts/derkino-services/
          helm lint deployment/helm-charts/derkino-ui/

      - name: Validate Ansible Playbooks
        uses: ansible/ansible-lint@v25.9.2
        with:
          working_directory: "deployment/ansible"

      - name: Ansible Playbook Syntax Check
        run: |
          cd deployment/ansible
          ansible-playbook --syntax-check deploy.yml -e "deployment_environment=local"

      - name: Ansible Playbook Dry-Run
        run: |
          cd deployment/ansible
          ansible-playbook --check deploy.yml -e "deployment_environment=local"

      - name: Validate Helm Templates
        run: |
          # The "helm template" command is a great smoke test for chart syntax
          helm template test-infra deployment/helm-charts/derkino-infrastructure/ > /dev/null
          helm template test-services deployment/helm-charts/derkino-services/ > /dev/null
          helm template test-ui deployment/helm-charts/derkino-ui/ > /dev/null
