name: Validate Helm Infrastructure

on:
  push:
    branches: [ master, main ]
    paths:
      - 'deployment/helm-charts/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'deployment/helm-charts/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: 'latest'
        
    - name: Add Bitnami Helm repository
      run: helm repo add bitnami https://charts.bitnami.com/bitnami
        
    - name: Build Helm dependencies
      # This step uses the Chart.lock file to ensure a reproducible build
      run: helm dependency build deployment/helm-charts/derkino-infrastructure
        
    - name: Lint Helm chart
      # This runs a static analysis of the chart and its dependencies
      run: helm lint --with-subcharts deployment/helm-charts/derkino-infrastructure
        
    - name: Template Helm chart for validation
      # This is the most powerful check. It ensures all templates can be
      # rendered into valid Kubernetes YAML without deploying anything.
      run: helm template --debug deployment/helm-charts/derkino-infrastructure
